server:
  port: 9988


security:
  user:
    password: ${password:config_password}
    name: user

#//log
log.spring.rabbitmq:
  host: 192.168.99.100
  port: 5672
  username: guest
  password: guest

#//sleuth
spring.rabbitmq:
  host: 192.168.99.100
  port: 5672
  username: guest
  password: guest